import { useEffect, useState } from "react";
import { AppShell } from "@/components/cspm/AppShell";
import { Button } from "@/components/ui/button";
import { Printer, ShieldCheck, AlertTriangle, FileBadge2, TrendingUp } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { scoreFramework, FRAMEWORK_META, type Framework, type FindingLite } from "@/lib/compliance";
import { format } from "date-fns";
import type { Database } from "@/integrations/supabase/types";

type Finding = Database["public"]["Tables"]["findings"]["Row"];
type Scan = Database["public"]["Tables"]["scans"]["Row"];

const FRAMEWORKS: Framework[] = ["SOC2", "ISO27001", "GDPR", "HIPAA"];

const BoardReport = () => {
  const [findings, setFindings] = useState<Finding[]>([]);
  const [scans, setScans] = useState<Scan[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    document.title = "Board Report — SentinelCSPM";
    (async () => {
      const [{ data: f }, { data: s }] = await Promise.all([
        supabase.from("findings").select("*"),
        supabase.from("scans").select("*").order("created_at", { ascending: false }).limit(50),
      ]);
      setFindings(f ?? []);
      setScans(s ?? []);
      setLoading(false);
    })();
  }, []);

  const counts = {
    critical: findings.filter(f => f.severity === "critical").length,
    high: findings.filter(f => f.severity === "high").length,
    medium: findings.filter(f => f.severity === "medium").length,
    low: findings.filter(f => f.severity === "low").length,
  };
  const score = Math.max(0, Math.round(100 - counts.critical * 8 - counts.high * 4 - counts.medium * 1.5 - counts.low * 0.4));
  const lite: FindingLite[] = findings.map(f => ({ rule_id: f.rule_id, compliance: f.compliance, severity: f.severity }));
  const frameworkScores = FRAMEWORKS.map(fw => ({ fw, ...scoreFramework(fw, lite) }));

  // Top risks: critical + high, dedup by rule_id
  const topRisksMap = new Map<string, Finding>();
  findings
    .filter(f => f.severity === "critical" || f.severity === "high")
    .forEach(f => { if (!topRisksMap.has(f.rule_id)) topRisksMap.set(f.rule_id, f); });
  const topRisks = Array.from(topRisksMap.values()).slice(0, 8);

  const completedScans = scans.filter(s => s.status === "completed");
  const verdict = score >= 85 ? "Strong" : score >= 70 ? "Solid with room to improve" : score >= 50 ? "Needs attention" : "Requires immediate action";
  const verdictColor = score >= 85 ? "text-severity-low" : score >= 70 ? "text-severity-info" : score >= 50 ? "text-severity-medium" : "text-severity-critical";

  if (loading) return <AppShell><div className="text-sm text-muted-foreground">Loading…</div></AppShell>;

  return (
    <AppShell>
      <div className="flex items-center justify-between mb-6 print:hidden">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Board / Investor Report</h1>
          <p className="text-muted-foreground mt-1">A one-page security posture summary you can share with investors, your board, or enterprise prospects.</p>
        </div>
        <Button onClick={() => window.print()}>
          <Printer className="w-4 h-4 mr-2" /> Print or save as PDF
        </Button>
      </div>

      <article className="surface-card p-8 md:p-12 print:p-0 print:bg-white print:text-black print:shadow-none print:border-0 max-w-4xl mx-auto report-page">
        {/* Header */}
        <header className="border-b border-border pb-6 mb-6 print:border-black/20">
          <div className="flex items-center justify-between mb-2">
            <div className="text-xs font-mono uppercase tracking-[0.18em] text-muted-foreground print:text-black/60">Security Posture Report</div>
            <div className="text-xs font-mono text-muted-foreground print:text-black/60">{format(new Date(), "MMMM d, yyyy")}</div>
          </div>
          <h2 className="text-3xl font-bold tracking-tight">Executive Summary</h2>
          <p className="mt-2 text-muted-foreground print:text-black/70">
            Generated by SentinelCSPM across cloud, code, container, and AI workflow assets.
          </p>
        </header>

        {/* Verdict */}
        <section className="mb-8 grid md:grid-cols-3 gap-6">
          <div className="md:col-span-1">
            <div className="text-xs font-mono uppercase tracking-wider text-muted-foreground print:text-black/60 mb-2">Posture Score</div>
            <div className={`text-6xl font-bold ${verdictColor} print:text-black`}>{score}</div>
            <div className={`text-sm font-semibold mt-1 ${verdictColor} print:text-black`}>{verdict}</div>
            <div className="text-xs text-muted-foreground print:text-black/60 mt-1">out of 100</div>
          </div>
          <div className="md:col-span-2 grid grid-cols-2 gap-3">
            <Stat label="Critical issues" value={counts.critical} accent="critical" />
            <Stat label="High issues" value={counts.high} accent="high" />
            <Stat label="Medium issues" value={counts.medium} accent="medium" />
            <Stat label="Scans completed" value={completedScans.length} accent="info" />
          </div>
        </section>

        {/* Compliance */}
        <section className="mb-8">
          <h3 className="text-lg font-semibold mb-3 flex items-center gap-2">
            <FileBadge2 className="w-4 h-4 text-primary print:text-black" /> Compliance Posture
          </h3>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
            {frameworkScores.map(({ fw, score, passing, total }) => (
              <div key={fw} className="border border-border rounded-md p-3 print:border-black/30">
                <div className="text-xs font-mono uppercase tracking-wider text-muted-foreground print:text-black/60">
                  {FRAMEWORK_META[fw].label}
                </div>
                <div className="text-2xl font-bold mt-1">{score}<span className="text-sm text-muted-foreground print:text-black/60">/100</span></div>
                <div className="text-[11px] text-muted-foreground print:text-black/60 mt-0.5">{passing}/{total} controls passing</div>
              </div>
            ))}
          </div>
        </section>

        {/* Top risks */}
        <section className="mb-8">
          <h3 className="text-lg font-semibold mb-3 flex items-center gap-2">
            <AlertTriangle className="w-4 h-4 text-severity-high print:text-black" /> Top Risks Requiring Attention
          </h3>
          {topRisks.length === 0 ? (
            <div className="border border-border rounded-md p-4 text-sm text-muted-foreground print:border-black/30 print:text-black/70 flex items-center gap-2">
              <ShieldCheck className="w-4 h-4 text-severity-low print:text-black" />
              No critical or high-severity findings detected.
            </div>
          ) : (
            <ol className="space-y-2">
              {topRisks.map((f, i) => (
                <li key={f.id} className="border border-border rounded-md p-3 print:border-black/30">
                  <div className="flex items-start gap-3">
                    <div className="text-xs font-mono text-muted-foreground print:text-black/60 mt-0.5 w-5 shrink-0">{String(i + 1).padStart(2, "0")}</div>
                    <div className="min-w-0 flex-1">
                      <div className="flex items-center gap-2 flex-wrap">
                        <span className="font-medium text-sm">{f.title}</span>
                        <span className={`text-[10px] font-mono uppercase px-1.5 py-0.5 rounded ${f.severity === "critical" ? "bg-severity-critical-bg text-severity-critical print:bg-transparent print:text-black print:border print:border-black" : "bg-severity-high-bg text-severity-high print:bg-transparent print:text-black print:border print:border-black"}`}>
                          {f.severity}
                        </span>
                      </div>
                      <div className="text-xs text-muted-foreground print:text-black/70 mt-1 line-clamp-2">{f.description}</div>
                    </div>
                  </div>
                </li>
              ))}
            </ol>
          )}
        </section>

        {/* Activity */}
        <section className="mb-8">
          <h3 className="text-lg font-semibold mb-3 flex items-center gap-2">
            <TrendingUp className="w-4 h-4 text-primary print:text-black" /> Scan Activity
          </h3>
          <div className="text-sm text-muted-foreground print:text-black/70">
            {completedScans.length} security scan{completedScans.length === 1 ? "" : "s"} completed across cloud, code, and container assets.
            {completedScans[0] && ` Most recent scan: ${format(new Date(completedScans[0].created_at), "MMM d, yyyy")}.`}
          </div>
        </section>

        <footer className="border-t border-border pt-4 text-xs text-muted-foreground print:border-black/20 print:text-black/60">
          This report is auto-generated from live findings. Numbers reflect the current state of the platform.
        </footer>
      </article>

      <style>{`
        @media print {
          @page { size: letter; margin: 0.6in; }
          body { background: white !important; }
          header, nav, .print\\:hidden { display: none !important; }
          .report-page { box-shadow: none !important; }
        }
      `}</style>
    </AppShell>
  );
};

const Stat = ({ label, value, accent }: { label: string; value: number; accent: "critical" | "high" | "medium" | "info" }) => {
  const accentMap = {
    critical: "text-severity-critical",
    high:     "text-severity-high",
    medium:   "text-severity-medium",
    info:     "text-severity-info",
  };
  return (
    <div className="border border-border rounded-md p-3 print:border-black/30">
      <div className="text-[11px] font-mono uppercase tracking-wider text-muted-foreground print:text-black/60">{label}</div>
      <div className={`text-2xl font-bold mt-1 ${accentMap[accent]} print:text-black`}>{value}</div>
    </div>
  );
};

export default BoardReport;
